# nixpacks.toml

# Define the phases for building the application
[phases.setup]
nixPkgs = ["nodejs_20", "npm"]
aptPkgs = []

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

# Define the start command for running the application
[start]
cmd = "npm start"
